---
title: "dRT Notes"
output:
  pdf_document: default
  html_notebook:
    fig_caption: yes
---

Understand difference between STAN and Ali's alignment

```{r, echo=TRUE}
suppressWarnings({
  library(tidyverse)
  library(reshape2)
  
  ev <- read_tsv('dat/evidence.txt')
  lib.ali <- read_tsv('dat/RT.lib.elite.txt')
  
  ev.stan <- read_tsv('dat/ev.adj.Fit2.txt')
  load('dat/params.Fit2.RData')
  
  # remove abnormal LC experiments
  # load experiments from correlation testing in similar.lc.R
  exps.lc <- unlist(read_csv('dat/exps.corr.txt')[,2])
  names(exps.lc) <- NULL
  
  ev <- ev %>%
    filter(grepl('[0-9]{6}A', `Raw file`)) %>% # Only use Elite experiments
    filter(`Raw file` %in% exps.lc) # Remove abnormal LC experiments
  
  ## Filter of PEP < .05
  ev.f <- ev %>% filter(PEP < 0.05) %>%
    filter(grepl('[0-9]{6}A', `Raw file`)) %>% # Only use Elite experiments
    filter(!grepl('REV*', `Leading razor protein`)) %>% # Remove Reverse matches
    filter(!grepl('CON*',`Leading razor protein`))  %>% # Remove Contaminants
    filter(`Raw file` %in% exps.lc) %>% # Remove abnormal LC experiments
    select("Peptide ID", "Raw file", "Retention time", "PEP", "Sequence") %>%
    mutate(exp_id=`Raw file`) %>%  # new column - exp_id = numeric version of experiment file
    mutate_at("exp_id", funs(as.numeric(as.factor(.))))
  
  experiment_factors <- as.factor(ev.f$`Raw file`)
  experiment_ids <- ev.f[["exp_id"]]
  num_exps <- length(unique(ev.f[["exp_id"]]))
  
  ## "true peptide id" matches peptide id in evidence file
  ## "peptide id" is index in 1:num_peptides for stan
  raw_peptide_id <- ev.f[["Peptide ID"]]
  pep.id.list <- unique(raw_peptide_id)
  stan_peptide_id <- as.numeric(as.factor(ev.f[["Peptide ID"]]))
  ev.f[["Stan ID"]] <- stan_peptide_id
  
  num_peptides <- length(unique(stan_peptide_id))
  
  pep_exp_all <- paste(stan_peptide_id, experiment_ids, sep=" - ")
  pep_exp_pairs <- unique(pep_exp_all)
  num_pep_exp_pairs <- length(pep_exp_pairs)
  muij_map <- match(paste(stan_peptide_id, experiment_ids, sep=" - "), pep_exp_pairs)
  splt <- strsplit(pep_exp_pairs, " - ")
  muij_to_pep <- as.numeric(sapply(splt, function(x) x[1]))
  muij_to_exp <- as.numeric(sapply(splt, function(x) x[2]))
})
```


```{r}
# get difference matrix, between library RTs and the canonical RTs
# for Ali's method, this is just the median RT for each peptide

# first coerce data matrix into numeric elements
# make sure to exclude sequence column, and statistics columns (4 at end)
lib.ali.dat <- matrix(as.numeric(unlist(lib.ali[,2:(ncol(lib.ali)-4)])), ncol=ncol(lib.ali)-5, nrow=nrow(lib.ali))
# get median RT for each peptide
lib.ali.med <- lib.ali$rt.median
# get difference matrix
lib.ali.diff <- lib.ali.dat - lib.ali.med

#plot(density(lib.ali.diff, na.rm=TRUE), type='l', col='red')
hist(lib.ali.diff, breaks=100, freq=FALSE)
```

```{r}
#lib.stan <- ev.stan[,c('Sequence','')]
# canonical RTs for each peptide
lib.stan.med <- pars[grep('mu\\[', names(pars))]
lib.stan.med <- as.numeric(unlist(lib.stan.med))

lib.stan <- ev.f[,c('Retention time', 'exp_id', 'Stan ID')]
# collapse retention times for same experiment and same peptide
# just use the median
lib.stan <- lib.stan %>% 
  group_by(`Stan ID`, exp_id) %>%
  summarise(RT=median(`Retention time`)) %>% 
  spread(exp_id, RT)
# remove key column - its the same as the row #
lib.stan <- lib.stan[,-1]
# turn into a proper matrix instead of weird tibble
lib.stan <- data.matrix(lib.stan)

# get difference matrix - subtract canonical retention times
# for each peptide from pars['mu[%d]']
lib.stan.diff <- lib.stan - lib.stan.med

# get difference matrix - use median RTs instead of canonical RTs
lib.stan.med.diff <- lib.stan - apply(lib.stan, 1, median, na.rm=TRUE)
```

```{r}
par(mfrow=c(1,3))
hist(lib.ali.diff, breaks=50, 
     main='Ali Method', xlab='Distance from Library (min)')
hist(lib.stan.diff, breaks=50, 
     main='STAN Fit2 - Canonical', xlab='Distance from Library (min)')
hist(lib.stan.med.diff, breaks=50,
     main='STAN Fit2 - Median', xlab='Distance from Library (min)')

par(mfrow=c(1,1))
plot(density(lib.ali.diff, na.rm=TRUE), xlim=c(-100, 150), ylim=c(0, 0.3), col='red', 
     main="Distance between Unaligned RT \nand Library RT")
lines(density(lib.stan.diff, na.rm=TRUE), col='blue')
lines(density(lib.stan.med.diff, na.rm=TRUE), col='green')
legend('topright', legend=c('Ali', 'STAN canonical', 'STAN median'), 
       col=c('red', 'blue', 'green'), pch=c('-', '-', '-'), pt.cex=3)

# get median difference from canonical retention time by median


```

```{r}
# do linear regression alignment

# Ali Method:
ev.ali <- read_tsv('dat/evidence+dRT.elite.txt')
lib.ali.corrected <- ev.ali %>%
  filter(Sequence %in% lib.ali$peptides) %>%
  group_by(Sequence, Raw.file) %>%
  summarise(RT=median(RT.corrected)) %>%
  spread(Raw.file, RT)
lib.ali.corrected <- data.matrix(lib.ali.corrected)

lib.ali.diff.corrected <- lib.ali.corrected - lib.ali$rt.median[sort(unique(match(ev.ali$Sequence, lib.ali$peptides))[-1])]

# STAN Method:
lib.stan.corrected <- ev.stan %>%
  mutate(RT=`Retention time`-muijs) %>%
  group_by(Sequence, `Raw file`) %>%
  summarise(RT=median(RT)) %>%
  spread(`Raw file`, RT)
lib.stan.corrected <- data.matrix(lib.stan.corrected)
```

```{r}
par(mfrow=c(1,1))
hist(lib.ali.diff.corrected, breaks=c(-200,seq(-100,100,by=2),200), freq=FALSE, col=rgb(0,1,0,0.5))
hist(lib.stan.corrected, breaks=c(-200,seq(-100,100,by=2),200), freq=FALSE, col=rgb(1,0,0,0.5), add=T)


par(mfrow=c(1,1))
plot(density(lib.ali.diff.corrected, na.rm=TRUE), xlim=c(-100, 100), ylim=c(0, 1), col='red', 
     main="Distance between Aligned RT \nand Library RT")
lines(density(lib.stan.corrected, na.rm=TRUE), col='blue')
legend('topright', legend=c('Ali', 'STAN canonical'), 
       col=c('red', 'blue'), pch=c('-', '-'), pt.cex=3)

```
