---
title: "Modified Peptides"
output: mod_pep
---

```{r}

library(tidyverse)
library(ggridges)
source('lib.R')


ev <- read_tsv('dat/ev.adj.Fit2.txt_old')
ev.mod <- read_tsv('dat/ev.adj.Fit2.txt')

## look for PSMs that get severely downgraded by our algorithm
peps <- ev %>%
  filter(PEP < 1e-5) %>%
  filter(PEP.new > 1e-3) %>%
  pull('Sequence')

ev.mod <- ev %>%
  group_by(Sequence) %>%
  summarise(num=length(Sequence), mods=length(unique(Modifications))) %>%
  filter(mods > 1) %>%
  arrange(desc(num))

```

```{r}

## take an example peptide and see how it compares between our two sets
# 1, 3
i <- 11
pep <- ev.mod[i,]$Sequence
exp <- ev[ev$Sequence==pep,]
exp %>%
  ggplot(aes(x=`Retention time`, y=Modifications, fill=Modifications)) +
  geom_density_ridges() +
  labs(title=paste('Retention time', pep), x='Retention Time (mins)')

```

```{r}
# Do some macro comparisons of using modified peptide ID
ev <- read_tsv('dat/ev.adj.Fit2.txt')
ev.seq <- ev %>%
  group_by(`Sequence`) %>%
  summarise(num.mods=length(unique(Modifications)), # number of unique modifications
            drt.med=median(abs(muijs-`Retention time`), na.rm=TRUE),
            dpep.med=median((PEP-PEP.new), na.rm=TRUE)) %>%
  filter(num.mods > 1) %>%
  arrange(desc(num.mods))

ev.mod <- ev %>%
  filter(Sequence %in% ev.seq$Sequence) %>%
  group_by(`Peptide ID`) %>%
  summarise(Sequence=first(Sequence),
            drt.med=median(abs(muijs-`Retention time`), na.rm=TRUE),
            dpep.med=median((PEP-PEP.new), na.rm=TRUE))

plot(density(ev.seq$drt.med, na.rm=TRUE), col='red')
lines(density(ev.mod$drt.med, na.rm=TRUE), col='blue')

# combine the two datasets and scatterplot

ev.tot <- ev.mod %>%
  rename(drt.mod=drt.med) %>%
  mutate(drt.orig=ev.seq$drt.med[match(ev.mod$Sequence, ev.seq$Sequence)]) %>%
  rename(dpep.mod=dpep.med) %>%
  mutate(dpep.orig=ev.seq$dpep.med[match(ev.mod$Sequence, ev.seq$Sequence)])

# dRT
ev.tot %>%
  ggplot(aes(x=drt.orig, y=drt.mod)) +
  geom_point(alpha=0.3) +
  geom_abline(slope=1, intercept=0, color='red') +
  scale_x_log10(limits=c(1e-2, 1e2), breaks=logseq(1e-2, 1e2, 5), labels=scales::comma) + 
  scale_y_log10(limits=c(1e-2, 1e2), breaks=logseq(1e-2, 1e2, 5), labels=scales::comma) + 
  annotation_logticks(sides='bl') +
  labs(title='RTLib: dRT (RT vs. Adjusted RT)\nModified vs. Sequence ID',
       x='dRT Sequence Only (mins)', y='dRT Modified Sequence (mins)') +
  theme_bert()

# dPEP
ev.tot %>%
  ggplot(aes(x=dpep.orig, y=dpep.mod)) +
  geom_point(alpha=0.3) +
  geom_abline(slope=1, intercept=0, color='red') +
  scale_x_log10(limits=c(1e-4, 1), breaks=logseq(1e-4, 1, 5), labels=scales::comma) + 
  scale_y_log10(limits=c(1e-4, 1), breaks=logseq(1e-4, 1, 5), labels=scales::comma) + 
  annotation_logticks(sides='bl') +
  labs(title='RTLib: dPEP (PEP.original - PEP.new)\nModified vs. Sequence ID',
       x='dPEP Sequence Only', y='dPEP Modified Sequence') +
  theme_bert()
```